import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import request from 'supertest';import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../server.js';import {parseGPX,paint,exportGPX} from '../geometry.js';import {classify,infer,fetchSuggestions} from '../osm.js';
const gpx=Buffer.from('<gpx><trk><name>Å &amp; Ö</name><trkseg><trkpt lat="58.4" lon="15.6"><ele>40</ele><time>2026</time></trkpt><trkpt lat="58.401" lon="15.6"><ele>50</ele></trkpt><trkpt lat="58.402" lon="15.6"><ele>44</ele></trkpt></trkseg></trk></gpx>');
test('GPX: elevations, track gaps, escaping and unsafe XML',()=>{const r=parseGPX(gpx);assert.ok(Math.abs(r.distance-222.39)<.1);assert.equal(r.ascent,10);assert.equal(r.descent,6);assert.equal(r.gpx_name,'Å & Ö');assert.equal(parseGPX(exportGPX({...r,name:r.gpx_name,description:'Test',cafes:[]})).gpx_name,r.gpx_name);const gaps=parseGPX('<gpx><trk><trkseg><trkpt lat="58" lon="15"/><trkpt lat="58.001" lon="15"/></trkseg><trkseg><trkpt lat="59" lon="16"/><trkpt lat="59.001" lon="16"/></trkseg></trk></gpx>');assert.ok(gaps.distance<223);assert.equal(gaps.ascent,null);assert.throws(()=>parseGPX('<!DOCTYPE gpx><gpx/>'));assert.throws(()=>parseGPX('<gpx>'));assert.throws(()=>parseGPX(gpx.toString().replace('58.4','NaN')));});
test('Surface classification: broader data without pretending paved means asphalt',()=>{assert.equal(classify({surface:'paved'}).kind,'gravel');assert.equal(classify({surface:'unpaved'}).kind,'gravel');assert.equal(classify({highway:'path'}).kind,'trail');assert.equal(classify({highway:'residential'}).kind,'unknown');assert.equal(classify({tracktype:'grade2'}).source,'osm-inferred');const points=parseGPX(gpx).points;const ways=[{tags:{surface:'asphalt'},geometry:[{lat:58.4,lon:15.6},{lat:58.402,lon:15.6}]}];const result=infer(points,ways);assert.equal(result.diagnostics.classified_percent,100);assert.equal(result.spans[0].kind,'asphalt');assert.throws(()=>infer(points,[{tags:{surface:'asphalt'}}]),/geometri/);const unknown=infer(points,[{tags:{highway:'road'},geometry:ways[0].geometry}]);assert.equal(unknown.diagnostics.matched_percent,100);assert.equal(unknown.diagnostics.classified_percent,0);});
test('Overpass query requests full geometry, no surface-only exclusion; failures preserve data',async()=>{let query;await fetchSuggestions(parseGPX(gpx).points,async(url,options)=>{query=options.body.get('data');return new Response(JSON.stringify({elements:[]}));});assert.match(query,/out body geom/);assert.ok(!query.includes('["surface"]'));await assert.rejects(fetchSuggestions(parseGPX(gpx).points,async()=>new Response('busy',{status:503})),/Inga underlag/);});
test('Node API, auth, mutation, export and existing SQLite compatibility',async()=>{const dir=mkdtempSync(path.join(tmpdir(),'ruttbank-'));let service;
 try{const prior=new DatabaseSync(path.join(dir,'routes.sqlite3'));prior.exec('CREATE TABLE routes (id TEXT PRIMARY KEY, fingerprint TEXT UNIQUE, payload TEXT NOT NULL)');const old={...parseGPX(gpx),id:'0123456789abcdef',name:'Befintlig rutt',description:'',location:'',category:'gravel',source_url:'',cafes:[],created:1,revision:1,surfaces:[{start:0,end:222.39,kind:'other',source:'manual'}]};prior.prepare('INSERT INTO routes VALUES (?,?,?)').run(old.id,'old',JSON.stringify(old));prior.close();writeFileSync(path.join(dir,'config.json'),JSON.stringify({secret:'old-secret',admin_code:'existing-code'}));
 service=createApp({dataDir:dir,suggest:async p=>infer(p,[{tags:{surface:'asphalt'},geometry:[{lat:58.4,lon:15.6},{lat:58.402,lon:15.6}]}])});assert.equal(service.adminCode,'existing-code');const agent=request.agent(service.app);let info=await agent.get('/api/session');const token=info.body.csrf;const hdr={'X-CSRF-Token':token};assert.equal((await agent.get('/api/routes')).body.routes[0].name,'Befintlig rutt');assert.equal((await agent.post('/api/login').set(hdr).send({password:'existing-code'})).status,200);
 let res=await agent.post('/api/routes').set(hdr).field('category','mtb').field('is_race_course','on').field('is_strava_segment','on').attach('file',gpx,'route.gpx');assert.equal(res.status,201,JSON.stringify(res.body));let r=res.body;assert.equal(r.surface_status,'complete');assert.equal(r.surfaces[0].kind,'asphalt');assert.equal(r.is_race_course,true);assert.equal(r.is_strava_segment,true);assert.equal(r.category,'mtb');const migrated=(await agent.get('/api/routes/0123456789abcdef')).body;assert.equal(migrated.surfaces[0].kind,'gravel');assert.equal(migrated.surfaces[0].source,'manual');
 res=await agent.patch('/api/routes/'+r.id).set(hdr).send({revision:r.revision,action:'surface',start:0,end:50,kind:'gravel'});assert.equal(res.status,200);r=res.body;
 res=await agent.post('/api/routes/'+r.id+'/suggest-surfaces').set(hdr).send({revision:r.revision});assert.equal(res.status,200);r=res.body;assert.equal(r.surfaces[0].kind,'gravel');assert.equal(r.surfaces.at(-1).kind,'asphalt');
 res=await agent.patch('/api/routes/'+r.id).set(hdr).send({revision:r.revision,action:'metadata',name:r.name,category:'mtb',is_race_course:false,is_strava_segment:false});assert.equal(res.status,200);r=res.body;assert.equal(r.is_race_course,false);assert.equal(r.is_strava_segment,false);
 const exported=await agent.get('/api/routes/'+r.id+'/download');assert.equal(exported.status,200);assert.ok(!exported.text?.includes('<time>'));
 assert.equal((await agent.patch('/api/routes/'+r.id).set(hdr).send({revision:1,action:'surface',start:0,end:1,kind:'unknown'})).status,409);
 assert.equal((await agent.delete('/api/routes/'+r.id).send({})).status,403);
 const visitor=request.agent(service.app);const visitorInfo=await visitor.get('/api/session');assert.equal((await visitor.delete('/api/routes/'+r.id).set('X-CSRF-Token',visitorInfo.body.csrf).send({})).status,401);
 for(const f of ['/app.js','/map-update.css','/vendor/leaflet.js'])assert.equal((await agent.get(f)).status,200);assert.equal((await agent.get('/data/config.json')).status,404);
 assert.equal((await agent.delete('/api/routes/'+r.id).set(hdr).send({})).status,200);
 }finally{service?.db.close();rmSync(dir,{recursive:true,force:true});}
});

test('Upload survives unavailable map service and persists an actionable status',async()=>{
 const dir=mkdtempSync(path.join(tmpdir(),'route-failure-'));const service=createApp({dataDir:dir,password:'test',suggest:async()=>{throw Error('Map service unavailable');}});
 try{const agent=request.agent(service.app);const info=await agent.get('/api/session');const hdr={'X-CSRF-Token':info.body.csrf};await agent.post('/api/login').set(hdr).send({password:'test'});
 const res=await agent.post('/api/routes').set(hdr).attach('file',gpx,'route.gpx');assert.equal(res.status,201);assert.equal(res.body.surface_status,'failed');assert.equal(res.body.surface_error,'Map service unavailable');assert.equal(res.body.surfaces[0].kind,'unknown');assert.equal((await agent.get('/api/routes/'+res.body.id)).body.surface_status,'failed');
 }finally{service.db.close();rmSync(dir,{recursive:true,force:true});}
});
